import { Montserrat, Plus_Jakarta_Sans, Space_Grotesk, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Map from "@/components/layout/Map";
import Footer from "@/components/layout/Footer";
import MapSection from "@/components/layout/MapSection";

const monsterrat = Montserrat({
  variable: "--font-monsterrat",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  style: ['italic', 'normal'],
  variable: '--font-jakarta'
})

const space = Space_Grotesk({
  variable: "--font-space",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['300',"400", "500", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <MapSection/>
        <Footer />
      </body>
    </html>
  );
}
